

--CREATE TEMPORARY TABLESPACE tbs_temp_01 TEMPFILE 'tbs_temp_01.dbf' SIZE 5M AUTOEXTEND ON;
--CREATE TABLESPACE tbs_perm_01 DATAFILE 'tbs_perm_01.dat' SIZE 20M ONLINE;
--
--CREATE USER ORACLE_SCHEMA IDENTIFIED BY password DEFAULT TABLESPACE tbs_perm_01 TEMPORARY TABLESPACE tbs_temp_01 QUOTA 20M on tbs_perm_01;
--
--SET ECHO ON
--GRANT CREATE SESSION TO ORACLE_SCHEMA;
--GRANT CREATE ANY TABLE TO ORACLE_SCHEMA;
--GRANT SELECT ANY TABLE TO ORACLE_SCHEMA;
--GRANT CREATE ANY VIEW TO ORACLE_SCHEMA;
--GRANT CREATE ANY TRIGGER TO ORACLE_SCHEMA;
--GRANT CREATE ANY PROCEDURE TO ORACLE_SCHEMA;
--GRANT CREATE SEQUENCE TO ORACLE_SCHEMA;
--GRANT CREATE SYNONYM TO ORACLE_SCHEMA;
--GRANT
--CREATE ANY TYPE TO
--ORACLE_SCHEMA;


-- SELECT * FROM V$NLS_PARAMETERS;



